### ISSUE TITLE
Hard error after running; bundle install --binstubs

### ISSUE THREAD

**Issue by WilsonBradley** [rapid7/metasploit-omnibus#76] opened 2018-08-16 12:05 UTC
Is this breaking because it's not running as a different user other than root?

root@localhost:~/metasploit-omnibus# bundle install --binstubs
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root users on
this machine.
Fetching https://github.com/rapid7/omnibus
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies....
Fetching addressable 2.3.8
Installing addressable 2.3.8
Fetching awesome_print 1.8.0
Installing awesome_print 1.8.0
Fetching aws-sigv4 1.0.3 (was 1.0.2)
Installing aws-sigv4 1.0.3 (was 1.0.2)
Fetching jmespath 1.4.0 (was 1.3.1)
Installing jmespath 1.4.0 (was 1.3.1)
Fetching aws-sdk-core 2.11.109 (was 2.10.134)
Installing aws-sdk-core 2.11.109 (was 2.10.134)
Fetching aws-sdk-resources 2.11.109 (was 2.10.134)
Installing aws-sdk-resources 2.11.109 (was 2.10.134)
Fetching aws-sdk 2.11.109 (was 2.10.134)
Installing aws-sdk 2.11.109 (was 2.10.134)
Fetching multipart-post 2.0.0
Installing multipart-post 2.0.0
Fetching faraday 0.9.2
Installing faraday 0.9.2
Fetching httpclient 2.6.0.1
Installing httpclient 2.6.0.1
Fetching berkshelf-api-client 1.3.1
Installing berkshelf-api-client 1.3.1
Fetching buff-extensions 1.0.0
Installing buff-extensions 1.0.0
Fetching hashie 3.5.7
Installing hashie 3.5.7
Fetching varia_model 0.4.1
Installing varia_model 0.4.1
Fetching buff-config 1.0.1
Installing buff-config 1.0.1
Fetching buff-ruby_engine 0.1.0
Installing buff-ruby_engine 0.1.0
Fetching buff-shell_out 0.2.0
Installing buff-shell_out 0.2.0
Fetching hitimes 1.2.6
Installing hitimes 1.2.6 with native extensions
Fetching timers 4.0.4
Installing timers 4.0.4
Fetching celluloid 0.16.0
Installing celluloid 0.16.0
Fetching nio4r 1.2.1
Installing nio4r 1.2.1 with native extensions
Fetching celluloid-io 0.16.2
Installing celluloid-io 0.16.2
Fetching cleanroom 1.0.0
Installing cleanroom 1.0.0
Fetching minitar 0.5.4
Installing minitar 0.5.4
Fetching sawyer 0.6.0
Installing sawyer 0.6.0
Fetching octokit 3.8.0
Installing octokit 3.8.0
Fetching retryable 2.0.4
Installing retryable 2.0.4
Fetching buff-ignore 1.2.0
Installing buff-ignore 1.2.0
Fetching fuzzyurl 0.9.0
Installing fuzzyurl 0.9.0
Fetching mixlib-config 2.2.5
Installing mixlib-config 2.2.5
Fetching mixlib-shellout 2.3.2
Installing mixlib-shellout 2.3.2
Fetching tomlrb 1.2.6
Installing tomlrb 1.2.6
Fetching chef-config 13.7.16
Installing chef-config 13.7.16
Fetching erubis 2.7.0
Installing erubis 2.7.0
Using json 2.1.0
Fetching mixlib-authentication 1.4.2
Installing mixlib-authentication 1.4.2
Fetching semverse 1.2.1
Installing semverse 1.2.1
Fetching ridley 4.4.2
Installing ridley 4.4.2
Fetching dep-selector-libgecode 1.3.1
Installing dep-selector-libgecode 1.3.1 with native extensions

Fetching ffi 1.9.21
Installing ffi 1.9.21 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.5.0/gems/ffi-1.9.21/ext/ffi_c
/usr/bin/ruby2.5 -r ./siteconf20180816-16668-rm0sec.rb extconf.rb
checking for ffi.h... no
checking for ffi.h in /usr/local/include,/usr/include/ffi... no
checking for shlwapi.h... no
checking for rb_thread_blocking_region()... no
checking for rb_thread_call_with_gvl()... yes
checking for rb_thread_call_without_gvl()... yes
creating extconf.h
creating Makefile

current directory: /var/lib/gems/2.5.0/gems/ffi-1.9.21/ext/ffi_c
make "DESTDIR=" clean

current directory: /var/lib/gems/2.5.0/gems/ffi-1.9.21/ext/ffi_c
make "DESTDIR="
Running autoreconf for libffi
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
configure.ac:376: warning: AC_PROG_LD is m4_require'd but not m4_defun'd
acinclude.m4:251: LIBFFI_CHECK_LINKER_FEATURES is expanded from...
acinclude.m4:349: LIBFFI_ENABLE_SYMVERS is expanded from...
configure.ac:376: the top level
configure.ac:376: warning: AC_PROG_LD is m4_require'd but not m4_defun'd
acinclude.m4:251: LIBFFI_CHECK_LINKER_FEATURES is expanded from...
acinclude.m4:349: LIBFFI_ENABLE_SYMVERS is expanded from...
configure.ac:376: the top level
autoreconf: configure.ac: tracing
configure.ac:376: warning: AC_PROG_LD is m4_require'd but not m4_defun'd
acinclude.m4:251: LIBFFI_CHECK_LINKER_FEATURES is expanded from...
acinclude.m4:349: LIBFFI_ENABLE_SYMVERS is expanded from...
configure.ac:376: the top level
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
configure.ac:376: warning: AC_PROG_LD is m4_require'd but not m4_defun'd
acinclude.m4:251: LIBFFI_CHECK_LINKER_FEATURES is expanded from...
acinclude.m4:349: LIBFFI_ENABLE_SYMVERS is expanded from...
configure.ac:376: the top level
configure.ac:41: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure:7624: error: possibly undefined macro: AC_PROG_LD
autoreconf: /usr/bin/autoconf failed with exit status: 1
make: *** [libffi.mk:7: "/var/lib/gems/2.5.0/gems/ffi-1.9.21/ext/ffi_c/libffi-arm-linux-gnueabihf"/.libs/libffi_convenience.a] Error 1

make failed, exit code 2

Gem files will remain installed in /var/lib/gems/2.5.0/gems/ffi-1.9.21 for inspection.
Results logged to /var/lib/gems/2.5.0/extensions/arm-linux/2.5.0/ffi-1.9.21/gem_make.out

An error occurred while installing ffi (1.9.21), and Bundler cannot continue.
Make sure that `gem install ffi -v '1.9.21'` succeeds before bundling.

In Gemfile:
  berkshelf was resolved to 3.3.0, which depends on
    solve was resolved to 1.2.1, which depends on
      dep_selector was resolved to 1.0.6, which depends on
        ffi
root@localhost:~/metasploit-omnibus#
root@localhost:~/metasploit-omnibus# gem install ffi -v '1.9.21'
Building native extensions. This could take a while...
ERROR:  Error installing ffi:
        ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.5.0/gems/ffi-1.9.21/ext/ffi_c
/usr/bin/ruby2.5 -r ./siteconf20180816-14517-rd54rm.rb extconf.rb
checking for ffi.h... no
checking for ffi.h in /usr/local/include,/usr/include/ffi... no
checking for shlwapi.h... no
checking for rb_thread_blocking_region()... no
checking for rb_thread_call_with_gvl()... yes
checking for rb_thread_call_without_gvl()... yes
creating extconf.h
creating Makefile

current directory: /var/lib/gems/2.5.0/gems/ffi-1.9.21/ext/ffi_c
make "DESTDIR=" clean

current directory: /var/lib/gems/2.5.0/gems/ffi-1.9.21/ext/ffi_c
make "DESTDIR="
Running autoreconf for libffi
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
configure.ac:376: warning: AC_PROG_LD is m4_require'd but not m4_defun'd
acinclude.m4:251: LIBFFI_CHECK_LINKER_FEATURES is expanded from...
acinclude.m4:349: LIBFFI_ENABLE_SYMVERS is expanded from...
configure.ac:376: the top level
configure.ac:376: warning: AC_PROG_LD is m4_require'd but not m4_defun'd
acinclude.m4:251: LIBFFI_CHECK_LINKER_FEATURES is expanded from...
acinclude.m4:349: LIBFFI_ENABLE_SYMVERS is expanded from...
configure.ac:376: the top level
autoreconf: configure.ac: tracing
configure.ac:376: warning: AC_PROG_LD is m4_require'd but not m4_defun'd
acinclude.m4:251: LIBFFI_CHECK_LINKER_FEATURES is expanded from...
acinclude.m4:349: LIBFFI_ENABLE_SYMVERS is expanded from...
configure.ac:376: the top level
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
configure.ac:376: warning: AC_PROG_LD is m4_require'd but not m4_defun'd
acinclude.m4:251: LIBFFI_CHECK_LINKER_FEATURES is expanded from...
acinclude.m4:349: LIBFFI_ENABLE_SYMVERS is expanded from...
configure.ac:376: the top level
configure.ac:41: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure:7624: error: possibly undefined macro: AC_PROG_LD
autoreconf: /usr/bin/autoconf failed with exit status: 1
make: *** [libffi.mk:7: "/var/lib/gems/2.5.0/gems/ffi-1.9.21/ext/ffi_c/libffi-arm-linux-gnueabihf"/.libs/libffi_convenience.a] Error 1

make failed, exit code 2

Gem files will remain installed in /var/lib/gems/2.5.0/gems/ffi-1.9.21 for inspection.
Results logged to /var/lib/gems/2.5.0/extensions/arm-linux/2.5.0/ffi-1.9.21/gem_make.out
root@localhost:~/metasploit-omnibus# bin/omnibus build metasploit-framework
-bash: bin/omnibus: No such file or directory

**Comment by jmartin-r7** [comment] 2018-09-28 23:12
While there is a failure to bundle the error you see is actually about permissions and environment restrictions of the dependency gem for `ffi`.  Not something this project can control.

Due to this packaging functions the build process actually expect to be performed as an unprivileged user interacting with a ruby environment manager like [rvm](https://rvm.io/) to mange gemsets with a least privilege approach.  Also builds can execute inside docker containers in Linux.  To get a clear picture of the development environment used here you can look a the dependencies installed in the `Dockerfile` objects of the repository. 

If you approach this from the standard user with `rvm` and still have issues getting the environment working feel free to ask question in the metasploit #slack team or on the metasploit IRC.

Closing as not a bug in this project.

**Closed by jmartin-r7** 2018-09-28 23:12 UTC
